### ISSUE TITLE
 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nekromoff** [BikeOttawa/stressmodel#4]
Using the suggested instructions in readme, stress level generation fails with:
```
/var/www/sub/maps/stressmodel/ltsanalyzer.js:161
    return (latlong[latlong.length - 1] === '0') ? parseFloat(latlong).toString() : latlong
                            ^

TypeError: Cannot read property 'length' of undefined
    at ltsanalyzer.formatLatLong (/var/www/sub/maps/stressmodel/ltsanalyzer.js:161:29)
    at ltsanalyzer.createLevelFiles (/var/www/sub/maps/stressmodel/ltsanalyzer.js:146:28)
    at ltsanalyzer.onCompleteLoadNodes (/var/www/sub/maps/stressmodel/ltsanalyzer.js:104:15)
    at emitNone (events.js:106:13)
    at module.exports.emit (events.js:208:7)
    at SAXStream.<anonymous> (/var/www/sub/maps/stressmodel/node_modules/xml2object/lib/xml2object.js:176:8)
    at emitNone (events.js:106:13)
    at SAXStream.emit (events.js:208:7)
    at SAXParser.SAXStream._parser.onend (/var/www/sub/maps/stressmodel/node_modules/sax/lib/sax.js:190:10)
    at emit (/var/www/sub/maps/stressmodel/node_modules/sax/lib/sax.js:624:35)
```

**Comment by nekromoff** [comment]
Alright, when I tried smaller bounding box (extract), it worked.
